// Generated by https://quicktype.io

class PopularModel {
  String? backdropPath;
  List<int>? genreIds;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  double? voteAverage;
  int? voteCount;

  PopularModel({
    this.backdropPath,
    this.genreIds,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.voteAverage,
    this.voteCount,
  });

  factory PopularModel.fromMap(Map<String, dynamic> map){
    return PopularModel(
      backdropPath: map['background_path'] ?? '', //qualeses
      id: map['id'],
      originalLanguage: map['original_languaje'],
      originalTitle: map['original_title'],
      overview: map['overview'],
      popularity: map['popularity'],
      posterPath: map['poster_path'] ?? '',
      releaseDate: map['release_date'],
      title: map['tile'],
      voteAverage: (map['vote_average'] is int)
      ? (map['vote_average'] as int).toDouble()
      : map['vote_average'],
      voteCount: map['vote_count']
    );
  }
}
